const KEY='fiiTrackerStateV02';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const pct=v=>(Number(v)||0).toLocaleString('pt-BR',{maximumFractionDigits:2})+'%';
const initial={entries:[],prices:{},goals:{target:100000,income:1000,monthly:1000}};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||structuredClone(initial);
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function toast(m){const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function nav(){ $$('#nav button').forEach(b=>b.onclick=()=>{ $$('#nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(s=>s.classList.remove('active'));$('#section-'+b.dataset.section).classList.add('active');const titles={dashboard:['Visão geral','Acompanhe sua carteira e teste cenários matemáticos.'],simulador:['Simulador','Teste cenários com premissas definidas por você.'],carteira:['Carteira','Posições calculadas a partir dos seus lançamentos.'],lancamentos:['Lançamentos','Registre compras, vendas, aportes e rendimentos.'],metas:['Metas','Acompanhe objetivos de patrimônio e aportes.'],educacao:['Educação','Conceitos e indicadores para estudo de FIIs.'],fontes:['Fontes Oficiais','Consulte instituições e referências oficiais.']};$('#page-title').textContent=titles[b.dataset.section][0];$('#page-subtitle').textContent=titles[b.dataset.section][1]})}
function portfolio(){const m={};state.entries.forEach(e=>{const t=(e.ticker||'').trim().toUpperCase();if(!t)return;m[t]??={ticker:t,qty:0,invested:0,dividends:0};if(e.type==='Compra'){m[t].qty+=(+e.qty||0);m[t].invested+=(+e.value||0)||((+e.qty||0)*(+e.price||0))}if(e.type==='Venda'){m[t].qty-=(+e.qty||0);m[t].invested-=((+e.value||0)||((+e.qty||0)*(+e.price||0)))}if(e.type==='Dividendo'||e.type==='Juros/Rendimento')m[t].dividends+=(+e.value||0)}return Object.values(m).map(p=>{p.qty=Math.max(0,p.qty);p.price=Number(state.prices[p.ticker]||0);p.current=p.qty*p.price;p.result=p.current-p.invested;p.returnPct=p.invested?p.result/p.invested*100:0;return p})}
function totals(){const ps=portfolio(), invest=state.entries.reduce((a,e)=>e.type==='Aporte'?a+(+e.value||0):a,0), dividends=state.entries.reduce((a,e)=>e.type==='Dividendo'||e.type==='Juros/Rendimento'?a+(+e.value||0):a,0);const current=ps.reduce((a,p)=>a+p.current,0), invested=ps.reduce((a,p)=>a+p.invested,0);return {ps,invest,dividends,current,invested,result:current-invested}}
function renderDashboard(){const t=totals();$('#dashboard-cards').innerHTML=[['Patrimônio atual',money(t.current)],['Total investido',money(t.invested)],['Resultado financeiro',money(t.result)],['Dividendos recebidos',money(t.dividends)]].map(([l,v])=>`<div class="card"><div class="metric-label">${l}</div><div class="metric">${v}</div></div>`).join('');const bars=[...t.ps].sort((a,b)=>b.current-a.current).slice(0,8);const max=Math.max(1,...bars.map(x=>x.current));$('#evolution').innerHTML=bars.length?bars.map(p=>`<div class="bar-col"><span style="height:${Math.max(8,p.current/max*85)}%" title="${p.ticker}: ${money(p.current)}"></span><small>${p.ticker}</small></div>`).join(''):`<div class="empty">Ainda não há posições com preço atual informado.</div>`;const totalCur=Math.max(1,t.current);$('#composition').innerHTML=bars.length?bars.map(p=>`<div><div class="row small"><span><strong>${p.ticker}</strong></span><span>${pct(p.current/totalCur*100)}</span></div><div class="bar"><span style="width:${p.current/totalCur*100}%"></span></div></div>`).join(''):`<div class="empty">Cadastre compras e preços atuais para visualizar a composição.</div>`;$('#recent-entries').innerHTML=state.entries.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Ticker</th><th>Valor</th></tr></thead><tbody>${state.entries.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(e=>`<tr><td>${e.date}</td><td>${e.type}</td><td>${e.ticker||'-'}</td><td>${money(e.value)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Ainda não há lançamentos.</div>`}
function simCalc(v){const months=Math.round(+v.years*12), r=(+v.rate||0)/100, initial=+v.initial||0, monthly=+v.monthly||0;let nominal=initial,totalA=initial;for(let m=1;m<=months;m++){totalA+=monthly;nominal= v.reinvest==='yes' ? nominal*(1+r)+monthly : nominal+monthly*(1+r)}const real=nominal/((1+(+v.inflation||0)/100)**v.years);return {months,nominal,real,totalA,earn:nominal-totalA,monthlyIncome:nominal*r}}
function renderSim(){const f=$('#sim-form'),v=Object.fromEntries(new FormData(f).entries()),r=simCalc(v);$('#sim-results').innerHTML=[['Patrimônio projetado',money(r.nominal)],['Total aportado',money(r.totalA)],['Rendimentos matemáticos',money(r.earn)]].map(([l,x])=>`<div class="card"><div class="metric-label">${l}</div><div class="metric">${x}</div></div>`).join('');const years=[2,5,10,20,30].filter(y=>y<=Math.max(5,+v.years));$('#scenario-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Prazo</th><th>Patrimônio nominal</th><th>Total aportado</th><th>Rendimentos simulados</th><th>Valor real</th></tr></thead><tbody>${years.map(y=>{const rr=simCalc({...v,years:y});return`<tr><td>${y} anos</td><td>${money(rr.nominal)}</td><td>${money(rr.totalA)}</td><td>${money(rr.earn)}</td><td>${money(rr.real)}</td></tr>`}).join('')}</tbody></table></div>`}
function renderPortfolio(){const t=totals();$('#portfolio-table').innerHTML=t.ps.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Ticker</th><th>Qtd.</th><th>Preço médio</th><th>Preço atual</th><th>Investido</th><th>Atual</th><th>Resultado</th><th>Rentab.</th><th>Dividendos</th></tr></thead><tbody>${t.ps.map(p=>`<tr><td><strong>${p.ticker}</strong></td><td>${p.qty.toLocaleString('pt-BR')}</td><td>${money(p.qty?p.invested/p.qty:0)}</td><td>${money(p.price)}</td><td>${money(p.invested)}</td><td>${money(p.current)}</td><td>${money(p.result)}</td><td>${pct(p.returnPct)}</td><td>${money(p.dividends)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Ainda não há posições. Registre uma compra em Lançamentos.</div>`}
function renderEntries(){ $('#entries-table').innerHTML=state.entries.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Tipo</th><th>Ticker</th><th>Qtd.</th><th>Preço</th><th>Valor</th><th></th></tr></thead><tbody>${state.entries.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<tr><td>${e.date}</td><td>${e.type}</td><td>${e.ticker||'-'}</td><td>${e.qty||0}</td><td>${money(e.price)}</td><td>${money(e.value)}</td><td><button class="btn danger small" onclick="delEntry('${e.id}')">Excluir</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">Nenhum lançamento cadastrado.</div>`}
function delEntry(id){state.entries=state.entries.filter(e=>e.id!==id);save();toast('Lançamento excluído')}
window.delEntry=delEntry;
function renderGoals(){const t=totals(),g=state.goals||initial.goals,p=Math.min(100,g.target?t.current/g.target*100:0);$('#goal-view').innerHTML=`<div class="kpi-list"><div class="row"><span>Patrimônio atual</span><strong>${money(t.current)}</strong></div><div class="row"><span>Meta</span><strong>${money(g.target)}</strong></div><div class="row"><span>Progresso</span><strong>${pct(p)}</strong></div><div class="bar"><span style="width:${p}%"></span></div><div class="row"><span>Valor restante</span><strong>${money(Math.max(0,g.target-t.current))}</strong></div><div class="row"><span>Meta de renda mensal</span><strong>${money(g.income)}</strong></div><div class="row"><span>Meta mensal de aporte</span><strong>${money(g.monthly)}</strong></div></div>`}
function renderAll(){renderDashboard();renderPortfolio();renderEntries();renderGoals();renderSim()}
function wire(){const dateField=$('#entry-form [name=date]');if(dateField)dateField.value=new Date().toISOString().slice(0,10);$('#entry-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());if(!v.value||+v.value<0){toast('Informe um valor válido');return}state.entries.push({...v,id:crypto.randomUUID()});save();e.currentTarget.reset();dateField.value=new Date().toISOString().slice(0,10);toast('Lançamento salvo')};$('#sim-form').onsubmit=e=>{e.preventDefault();renderSim();toast('Projeção atualizada')};$('#sim-reset').onclick=()=>{$('#sim-form').reset();renderSim()};$('#goal-form').onsubmit=e=>{e.preventDefault();state.goals=Object.fromEntries(new FormData(e.currentTarget).entries());state.goals.target=+state.goals.target;state.goals.income=+state.goals.income;state.goals.monthly=+state.goals.monthly;save();toast('Metas salvas')};$('#new-entry').onclick=()=>{document.querySelector('[data-section=lancamentos]').click();window.scrollTo({top:0,behavior:'smooth'})};$('#export-data').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fii-investment-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)};$('#update-price').onclick=()=>{const ps=portfolio();$('#modal-title').textContent='Atualizar preços atuais';$('#modal-body').innerHTML=ps.length?`<form class="form" id="price-form">${ps.map(p=>`<div class="field"><label>${p.ticker}</label><input name="${p.ticker}" type="number" step="0.01" min="0" value="${p.price||''}"></div>`).join('')}<button class="btn primary" type="submit">Salvar preços</button></form>`:'<div class="empty">Cadastre ao menos uma posição primeiro.</div>';$('#modal').classList.add('show');const pf=$('#price-form');if(pf)pf.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget).entries());state.prices={...state.prices,...Object.fromEntries(Object.entries(v).map(([k,x])=>[k,+x||0]))};save();$('#modal').classList.remove('show');toast('Preços atualizados')}};$('#modal-close').onclick=()=>$('#modal').classList.remove('show');nav();renderAll()}
wire();
